// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mmApi.Model;

#nullable disable

namespace mmApi.Migrations
{
    [DbContext(typeof(timeTableDb))]
    partial class timeTableDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("mmApi.Model.timeTable", b =>
                {
                    b.Property<string>("tableVisitToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("dateSelection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("existingSelection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("maxCollaborator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("meetingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("state")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tableManageToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("timeRange")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("tableVisitToken");

                    b.ToTable("timeTables");
                });
#pragma warning restore 612, 618
        }
    }
}
